import type { SubscriptionType } from '../services/oauth/types.js';
import type { OverageDisabledReason } from './claudeAiLimits.js';
type MockHeaders = {
    'anthropic-ratelimit-unified-status'?: 'allowed' | 'allowed_warning' | 'rejected';
    'anthropic-ratelimit-unified-reset'?: string;
    'anthropic-ratelimit-unified-representative-claim'?: 'five_hour' | 'seven_day' | 'seven_day_opus' | 'seven_day_sonnet';
    'anthropic-ratelimit-unified-overage-status'?: 'allowed' | 'allowed_warning' | 'rejected';
    'anthropic-ratelimit-unified-overage-reset'?: string;
    'anthropic-ratelimit-unified-overage-disabled-reason'?: OverageDisabledReason;
    'anthropic-ratelimit-unified-fallback'?: 'available';
    'anthropic-ratelimit-unified-fallback-percentage'?: string;
    'retry-after'?: string;
    'anthropic-ratelimit-unified-5h-utilization'?: string;
    'anthropic-ratelimit-unified-5h-reset'?: string;
    'anthropic-ratelimit-unified-5h-surpassed-threshold'?: string;
    'anthropic-ratelimit-unified-7d-utilization'?: string;
    'anthropic-ratelimit-unified-7d-reset'?: string;
    'anthropic-ratelimit-unified-7d-surpassed-threshold'?: string;
    'anthropic-ratelimit-unified-overage-utilization'?: string;
    'anthropic-ratelimit-unified-overage-surpassed-threshold'?: string;
};
export type MockHeaderKey = 'status' | 'reset' | 'claim' | 'overage-status' | 'overage-reset' | 'overage-disabled-reason' | 'fallback' | 'fallback-percentage' | 'retry-after' | '5h-utilization' | '5h-reset' | '5h-surpassed-threshold' | '7d-utilization' | '7d-reset' | '7d-surpassed-threshold';
export type MockScenario = 'normal' | 'session-limit-reached' | 'approaching-weekly-limit' | 'weekly-limit-reached' | 'overage-active' | 'overage-warning' | 'overage-exhausted' | 'out-of-credits' | 'org-zero-credit-limit' | 'org-spend-cap-hit' | 'member-zero-credit-limit' | 'seat-tier-zero-credit-limit' | 'opus-limit' | 'opus-warning' | 'sonnet-limit' | 'sonnet-warning' | 'fast-mode-limit' | 'fast-mode-short-limit' | 'extra-usage-required' | 'clear';
export declare function setMockHeader(key: MockHeaderKey, value: string | undefined): void;
export declare function addExceededLimit(type: 'five_hour' | 'seven_day' | 'seven_day_opus' | 'seven_day_sonnet', hoursFromNow: number): void;
export declare function setMockEarlyWarning(claimAbbrev: '5h' | '7d' | 'overage', utilization: number, hoursFromNow?: number): void;
export declare function clearMockEarlyWarning(): void;
export declare function setMockRateLimitScenario(scenario: MockScenario): void;
export declare function getMockHeaderless429Message(): string | null;
export declare function getMockHeaders(): MockHeaders | null;
export declare function getMockStatus(): string;
export declare function clearMockHeaders(): void;
export declare function applyMockHeaders(headers: globalThis.Headers): globalThis.Headers;
export declare function shouldProcessMockLimits(): boolean;
export declare function getCurrentMockScenario(): MockScenario | null;
export declare function getScenarioDescription(scenario: MockScenario): string;
export declare function setMockSubscriptionType(subscriptionType: SubscriptionType | null): void;
export declare function getMockSubscriptionType(): SubscriptionType | null;
export declare function shouldUseMockSubscription(): boolean;
export declare function setMockBillingAccess(hasAccess: boolean | null): void;
export declare function isMockFastModeRateLimitScenario(): boolean;
export declare function checkMockFastModeRateLimit(isFastModeActive?: boolean): MockHeaders | null;
export {};
//# sourceMappingURL=mockRateLimits.d.ts.map