export declare const COMMAND_NAME_TAG = "command-name";
export declare const COMMAND_MESSAGE_TAG = "command-message";
export declare const COMMAND_ARGS_TAG = "command-args";
export declare const BASH_INPUT_TAG = "bash-input";
export declare const BASH_STDOUT_TAG = "bash-stdout";
export declare const BASH_STDERR_TAG = "bash-stderr";
export declare const LOCAL_COMMAND_STDOUT_TAG = "local-command-stdout";
export declare const LOCAL_COMMAND_STDERR_TAG = "local-command-stderr";
export declare const LOCAL_COMMAND_CAVEAT_TAG = "local-command-caveat";
export declare const TERMINAL_OUTPUT_TAGS: readonly ["bash-input", "bash-stdout", "bash-stderr", "local-command-stdout", "local-command-stderr", "local-command-caveat"];
export declare const TICK_TAG = "tick";
export declare const TASK_NOTIFICATION_TAG = "task-notification";
export declare const TASK_ID_TAG = "task-id";
export declare const TOOL_USE_ID_TAG = "tool-use-id";
export declare const TASK_TYPE_TAG = "task-type";
export declare const OUTPUT_FILE_TAG = "output-file";
export declare const STATUS_TAG = "status";
export declare const SUMMARY_TAG = "summary";
export declare const REASON_TAG = "reason";
export declare const WORKTREE_TAG = "worktree";
export declare const WORKTREE_PATH_TAG = "worktreePath";
export declare const WORKTREE_BRANCH_TAG = "worktreeBranch";
export declare const ULTRAPLAN_TAG = "ultraplan";
export declare const REMOTE_REVIEW_TAG = "remote-review";
export declare const REMOTE_REVIEW_PROGRESS_TAG = "remote-review-progress";
export declare const TEAMMATE_MESSAGE_TAG = "teammate-message";
export declare const CHANNEL_MESSAGE_TAG = "channel-message";
export declare const CHANNEL_TAG = "channel";
export declare const CROSS_SESSION_MESSAGE_TAG = "cross-session-message";
export declare const FORK_BOILERPLATE_TAG = "fork-boilerplate";
export declare const FORK_DIRECTIVE_PREFIX = "Your directive: ";
export declare const COMMON_HELP_ARGS: string[];
export declare const COMMON_INFO_ARGS: string[];
//# sourceMappingURL=xml.d.ts.map