import { useState } from 'react';

interface ChatInputProps {
  agentName: string;
  onSend: (content: string) => void;
  disabled?: boolean;
}

export function ChatInput({ agentName, onSend, disabled }: ChatInputProps) {
  const [inputText, setInputText] = useState('');

  const handleSend = () => {
    if (!inputText.trim() || disabled) return;
    onSend(inputText.trim());
    setInputText('');
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey && !e.nativeEvent.isComposing) {
      e.preventDefault();
      handleSend();
    }
  };

  return (
    <div className="p-6 pt-0 bg-transparent shrink-0 w-full max-w-4xl flex flex-col">
      <div className="relative flex items-end gap-2 bg-ivory rounded-2xl p-2 border border-border-cream shadow-sm focus-within:ring-1 focus-within:ring-border-cream transition-all w-full">
        <button className="p-2 text-stone hover:text-charcoal hover:bg-surface-container rounded-full transition-colors mb-0.5 shrink-0">
          <span className="material-symbols-outlined text-[20px]">attach_file</span>
        </button>
        <textarea
          className="w-full bg-transparent border-transparent focus:ring-0 resize-none text-sm py-2.5 px-2 max-h-[120px] outline-none text-charcoal placeholder:text-stone/60 custom-scrollbar"
          placeholder={`Message ${agentName}...`}
          rows={1}
          style={{ minHeight: '44px' }}
          value={inputText}
          onChange={(e) => setInputText(e.target.value)}
          onKeyDown={handleKeyDown}
        />
        <button
          onClick={handleSend}
          disabled={!inputText.trim() || disabled}
          className="w-9 h-9 bg-charcoal disabled:opacity-50 text-white rounded-xl flex items-center justify-center hover:opacity-90 active:scale-95 transition-all shrink-0 mb-0.5"
        >
          <span className="material-symbols-outlined text-[18px]">send</span>
        </button>
      </div>
      <div className="mt-2 text-center">
        <span className="text-[10px] text-stone/70">Content generated by AI, please verify</span>
      </div>
    </div>
  );
}
